### ISSUE TITLE
validare il csv delle scuole primarie

### ISSUE THREAD

**Issue by olistik** [comune-desio/opendata#11]
Un paio di dubbi sulla consistenza di https://github.com/comune-desio/opendata/blob/master/scuole-primarie.csv
## duplicazione

Le coppie di record:
- [1](https://github.com/comune-desio/opendata/blob/master/scuole-primarie.csv#L2) e [2](https://github.com/comune-desio/opendata/blob/master/scuole-primarie.csv#L3)
- [3](https://github.com/comune-desio/opendata/blob/master/scuole-primarie.csv#L4) e [4](https://github.com/comune-desio/opendata/blob/master/scuole-primarie.csv#L5)
- [5](https://github.com/comune-desio/opendata/blob/master/scuole-primarie.csv#L6) e [6](https://github.com/comune-desio/opendata/blob/master/scuole-primarie.csv#L7)

sembrano essere relative allo stesso "ISTITUTO COMPRENSIVO STATALE / SCUOLA PARITARIA", cambia solo il plesso.
## numero civico

I record [3](https://github.com/comune-desio/opendata/blob/master/scuole-primarie.csv#L4) e [4](https://github.com/comune-desio/opendata/blob/master/scuole-primarie.csv#L5) sono sprovvisti del numero civico.

**Comment by favoeva** [comment]
@olistik sì corretto cambia il plesso e quindi la scuola reale. Es. Istituto omnicomprensivo "X": plesso scuola materna, plesso scuola elementare, plesso scuola media. Per i record 3 e 4 cercherò i civici chiedendoli direttamente alle segreterie (sui loro siti mancano)

**Comment by favoeva** [comment]
indirizzo corretto scuola primaria Via prati: Via Prati snc (senza numero civico) è posizionata all'angolo con via Dal Verme
indirizzo completo scuola primaria via Sant'Apollinare: Via Sant'Apollinare n° 10

**Comment by olistik** [comment]
Ok, sembra che finalmente le scuole desiane si trovino a Desio ;-)

[scuole-primarie.geojson](https://github.com/comune-desio/opendata/blob/d9a3fed47eb9464986ef92da724da8ecefd7f22a/scuole-primarie.geojson)

<img width="778" alt="screen shot 2016-10-31 at 11 34 18" src="https://cloud.githubusercontent.com/assets/21038/19851399/05fb850c-9f5e-11e6-82e0-111fb592d613.png">

Ho anche strutturato un po' meglio le informazioni presenti.

Il geojson è stato ottenuto con [questo script di conversione](https://github.com/comune-desio/utilita/blob/304e8535c0a0dd26623e7a6ed6f6cc2610bce0fe/csv2geojson--scuole.rb)
