### ISSUE TITLE
Inserire il dataset dei parcometri

### ISSUE THREAD

**Issue by olistik** [comune-desio/opendata#15]
[PARCOMETRI DESIO.xlsx](https://github.com/comune-desio/opendata/files/193742/PARCOMETRI.DESIO.xlsx)

**Comment by ipersoft** [comment]
@olistik questo lo possiamo chiudere?

**Comment by olistik** [comment]
@ipersoft sì, corrisponde al dataset [parking.csv](https://github.com/comune-desio/opendata/blob/master/parking.csv), chiudo.
