### ISSUE TITLE
Inserire il dataset del menu delle scuole

### ISSUE THREAD

**Issue by olistik** [comune-desio/opendata#16]
- [x] [Estivo](http://www.comune.desio.mb.it/upload/desio/gestionedocumentale/MENUESTIVO2016-2017_784_7427.pdf)
- [x] [Invernale](http://www.comune.desio.mb.it/upload/desio/gestionedocumentale/MENUINVERNALE2016-2017_784_7434.pdf)
- modifichiamo il menù sul CMS togliendo la distinzione tra le scuole
- specifichiamo nella descrizione iniziale il periodo di validità
- prevediamo due sezioni: "menù estivo (corrente)" e "menù invernale", così possiamo inserirli da subito e in seguito aggiorniamo solo le etichette dei bottoni e la loro posizione

(Issue aggiornata in seguito alla rettifica ricevuta)

**Comment by favoeva** [comment]
mi devo ricordare di mandarti il menù nuovo delle scuole perchè un bot su questo continuo a vederlo benissimo! 

si può fare con menù bot
- menù mensa scolastica scuole elementari Desio
- menù mensa scolastica scuole medie
- intera settimana 
- giorno specifico 

?

**Comment by favoeva** [comment]
fino al 29 ottobre usiamo quello che abbiamo già @olistik @ipersoft https://github.com/comune-desio/opendata/files/193744/MENU.INVERNALE.IN.VIGORE.DAL.26.OTTOBRE.AL.9.APRLE.1015-1016.SCUOLE.PRIMARIE.E.SECONDARIE.xlsx

**Comment by olistik** [comment]
Rettifica con il documento unificato: http://www.comune.desio.mb.it/upload/desio/gestionedocumentale/MENUESTIVO2016-2017_784_7427.pdf
- modifichiamo il menù sul CMS togliendo la distinzione tra le scuole
- specifichiamo nella descrizione iniziale il periodo di validità
- prevediamo due sezioni: "menù estivo (corrente)" e "menù invernale", così possiamo inserirli da subito e in seguito aggiorniamo solo le etichette dei bottoni e la loro posizione

**Comment by favoeva** [comment]
ok abbiamo già anche il menù invernale http://www.comune.desio.mb.it/upload/desio/gestionedocumentale/MENUINVERNALE2016-2017_784_7434.pdf

**Comment by favoeva** [comment]
ok questa la prima riga description in:
_menù valido dal 5 Settembre al 21 Ottobre 2016 e dal 18 Aprile 2017 al 30 Giugno 2017_
_menù valido dal 24 Ottobre 2016 al 14 Aprile 2017_

**Comment by olistik** [comment]
@ipersoft @favoeva i menù dovrebbero essere stati aggiornati, il primo di voi che mi fa una review può chiudere la issue :-)

**Comment by olistik** [comment]
Per concludere questa attività bisogna prima esportare su un repository i dati contenuti nel [CMS del Bot](https://admin.bot.desio.org)

**Comment by ipersoft** [comment]
Bisogna spostare il menu togliendo l'estivo e mettendo l'altro.

**Comment by olistik** [comment]
@ipersoft fatto. La parte estiva è solo nascosta.
@favoeva quando pensi che arriverà il nuovo menù estivo?
