### ISSUE TITLE
Definire uno schema generico per i dataset

### ISSUE THREAD

**Issue by olistik** [comune-desio/opendata#17]
Lo schema dovrebbe permettere di specificare sia il formato (ad esempio: JSON, CSV o XML) che gli attributi (nome e tipo) dei dati che il dataset deve gestire.

Deve essere inoltre prevista la specifica dei meta dati necessari come ad esempio l'autore, la data di aggiornamento ed eventuali note aggiuntive.

**Comment by favoeva** [comment]
Linee guida nazionali per la valorizzazione del patrimonio informativo pubblico: a pagina 39 ci sono i metadati obbligatori per le PA [http://www.agid.gov.it/sites/default/files/linee_guida/patrimoniopubblicolg2014_v0.7finale.pdf]

**Comment by olistik** [comment]
spostato sulla [card Trello](https://trello.com/c/XcCpPGxl/4-definizione-di-uno-schema-per-i-dataset)
