### ISSUE TITLE
Rimuovere la duplicazione dei file geojson

### ISSUE THREAD

**Issue by olistik** [comune-desio/opendata#2]
Attualmente sono presenti due file `.geojson`:
1. https://github.com/comune-desio/opendata/blob/master/20160219-defibrillatori.geojson
2. https://github.com/comune-desio/opendata/blob/master/defibrillatori.DEF.geojson

Il file `.geojson` https://github.com/comune-desio/opendata/blob/master/20160219-defibrillatori.geojson è stato convertito a partire dal file `.csv` https://github.com/comune-desio/opendata/blob/master/20160219-defibrillatori.csv, usando lo script Ruby [csv2gejson.rb](https://github.com/comune-desio/utilita/blob/master/csv2geojson.rb).

Per essere sempre allineati sarebbe meglio apportare le modifiche ad un unico file d'origine (il `.csv` in questo caso) ed effettuare le necessarie conversioni a partire da quello.

Quindi, sarebbe sensato cancellare https://github.com/comune-desio/opendata/blob/master/defibrillatori.DEF.geojson e aggiornare https://github.com/comune-desio/opendata/blob/master/20160219-defibrillatori.geojson tramite lo script di conversione.

@favoeva se per te è ok aggiorno/cancello :-)

**Comment by favoeva** [comment]
Perfetto! Grazie anche per la spiegazione :) così inizio ad imparare

Il lunedì 22 febbraio 2016, Maurizio De Magnis notifications@github.com
ha scritto:
