### ISSUE TITLE
Conversione CSV -> GEOJSON

### ISSUE THREAD

**Issue by ipersoft** [comune-desio/opendata#26]
Utilizzando i CSV in opendata creare il tracciato JSON per la mappa
- [ ] defibrillatori.csv
- [ ] parking.csv
- [ ] scuole-primarie.csv
- [ ] scuole-secondarie--primo-grado.csv
- [ ] scuole-secondarie--secondo-grado.csv

@olistik travis o altro

**Comment by olistik** [comment]
@ipersoft riesci ad elencare i CSV a cui ti riferisci?

**Comment by ipersoft** [comment]
Per adesso mi sembra che abbiamo questi a disposizione. Per ognuno ci sarà da fare una importazione diversa per riportarli su uno standard per la mappa.
Le scuole le metterei raggruppate. I vari UUID non servono portati per la visualizzazione della mappa.
Volendo si può migliorare il pannello che si apre per inserire ulteriori dati. @favoeva 
- [ ] defibrillatori.csv
- [ ] parking.csv
- [ ] scuole-primarie.csv
- [ ] scuole-secondarie--primo-grado.csv
- [ ] scuole-secondarie--secondo-grado.csv

**Comment by olistik** [comment]
@ipersoft con la notazione:

```
- [ ] item 1
- [ ] item 2
- [ ] item 3
```

è possibile creare delle liste di checkbox che possono poi essere aggiornate.
Ho modificato il tuo ultimo commento e inserito la stessa lista nel commento originale.

**Comment by olistik** [comment]
@ipersoft 

> ci sarà da fare una importazione diversa per riportarli su uno standard per la mappa.

Stiamo parlando di [questo standard](https://github.com/comune-desio/map/blob/master/poi.json), giusto?

> Le scuole le metterei raggruppate.

Quindi nella stessa `Category`?

> I vari UUID non servono portati per la visualizzazione della mappa.

Diciamo che tenere gli UUID non ci costa nulla e ci permette anzi di effettuare conversioni bidirezionali, quindi sarebbe meglio tenere la maggior parte delle informazioni possibili, specialmente gli UUID.

> @olistik travis o altro

Per il sistema di build, vedo queste opzioni:
1. se ci interessa che i JSON convertiti siano presenti su GitHub, possiamo usare Travis e far confluire i JSON risultanti in un branch a parte (non ricordo però il repository dove ho impostato questo automatismo..)
2. se _non_ ci interessa che i JSON convertiti siano presenti su GitHub, possiamo usare molto più facilmente il sistema di build di Netlify

**Comment by ipersoft** [comment]
@olistik 
Standard corretto poi.json

Le scuole raggruppate andrebbero nello stesso dataset ma con categorie diverse
Volendo si può studiare anche la possibilità di non visualizzare le singole categorie

Il json non interessa se non c'è su github perché servirebbe solo per la mappa.

Per le modifiche farei affidamento sulla modifica sui CSV che mi sembra la cosa più facile e veloce da fare. 

Su Netlify andrebbe tutto il sito o solo il json?

**Comment by olistik** [comment]
@ipersoft 

> Le scuole raggruppate andrebbero nello stesso dataset ma con categorie diverse. Volendo si può studiare anche la possibilità di non visualizzare le singole categorie

Ok, quindi ogni CSV in un JSON a parte tranne che per le scuole che vengono suddivise nello stesso JSON con differenti `Category`.

> Per le modifiche farei affidamento sulla modifica sui CSV che mi sembra la cosa più facile e veloce da fare.

Ha senso 👍 

> Su Netlify andrebbe tutto il sito o solo il json?

Quello che vogliamo.

**Comment by olistik** [comment]
penso di poter chiudere questa issue dato che delegheremo la creazione di viste al portale dati.lombardia.it
