### ISSUE TITLE
creare una pagina statica con il grafico delle statistiche della polizia

### ISSUE THREAD

**Issue by olistik** [comune-desio/opendata#4]
Il dataset: https://github.com/comune-desio/opendata/blob/master/Statistiche_Polizia_Locale_Citta_di_Desio_attivita_2006-2014.csv
Una possibile libreria: http://www.chartjs.org/docs/

**Comment by favoeva** [comment]
Bene! Dici che è possibile fare una line chart?

**Comment by olistik** [comment]
@favoeva il [Line Chart](http://www.chartjs.org/docs/#line-chart) mi sembra una buona idea, ma dato che le sezioni sono numerose (43) potremmo farne uno per ogni sezione, che ne dici?

**Comment by favoeva** [comment]
@olistik potrei raggruppare per tipologia (codice della strada, polizia ambientale, polizia giudiziaria ecc.) e fare più di un csv . Questo perchè alcuni dati sono davvero quantitativamente poco significativi. Che ne pensi?

**Comment by olistik** [comment]
@favoeva a livello di visualizzazione grafica, il fatto che sia un `csv` o che siano più di uno non è rilevante.
Se però vuoi mantenere un grafico per ogni tipologia, allora :+1: :-)

**Comment by favoeva** [comment]
Ok allora provo a mandarti lista di categorie da visualizzare nella
prima chart . Direi di Cominciare  con il grafico relativo alle categorie
codice della strada, se sei d'accordo

Il lunedì 22 febbraio 2016, Maurizio De Magnis notifications@github.com
ha scritto:

**Comment by olistik** [comment]
@favoeva per ogni riga del `csv` c'è per caso un codice identificativo? Servirebbe per referenziare più precisamente ogni singola riga. Qualora non ci fosse userei un numero incrementale (da 1 a 43).

**Comment by favoeva** [comment]
@olistik fammi pensare... Un codice non ce l'hanno, ma forse sarebbe utile crearlo. Che ne dici , posso crearli e inserirli direttamente nel csv al posto dei numeri incrementali? domani ti mando lista righe per la prima line chart

**Comment by favoeva** [comment]
@olistik sono un po' indietro su questo. Pensavo di parlarne anche con il comandante Polizia Locale, magari hanno già dei codici utilizzati anche per scambio dati fra comandi e altre forze pubblica sicurezza ... tra l'altro forse questo giovedì avrò i dati attività 2015 :)

**Comment by olistik** [comment]
https://statistiche-polizia-desio.netlify.com/
Il repository dell'applicazione si trova su GitLab: https://gitlab.com/olistik/desio-polizia-locale

@favoeva @ipersoft quando potete datemi feedback grafici e sui dati :-)

**Comment by olistik** [comment]
per ora lo chiudo, la pagina con i grafici non è responsabilità di questo repository
