### ISSUE TITLE
Convertire i dataset scuole xls in CSV

### ISSUE THREAD

**Issue by favoeva** [comune-desio/opendata#5]
[dataset SCUOLE DESIO.zip](https://github.com/comune-desio/opendata/files/153190/dataset.SCUOLE.DESIO.zip)

**Comment by favoeva** [comment]
@olistik ho caricato tre data set riguardanti le scuole dei diversi ordini presenti in Città.

**Comment by olistik** [comment]
@favoeva sono 3 .xls che potrebbero confluire nello stesso documento? Sono tutti record relativi agli istituti scolastici, giusto?

**Comment by favoeva** [comment]
No li terrei separati

Il mercoledì 2 marzo 2016, Maurizio De Magnis notifications@github.com ha
scritto:

**Comment by olistik** [comment]
Quali sono le differenze semantiche dei file? Te lo chiedo per poterli catalogare adeguatamente :-)

**Comment by favoeva** [comment]
@olistik
scuole primarie (ex elementari) 
scuole secondarie di primo grado (ex Medie)
scuole secondarie di secondo grado (ex Superiori)

**Comment by olistik** [comment]
:+1:

**Comment by favoeva** [comment]
@olistik manca solo il dataset scuole dell'infanzia paritarie e comunali (scuole materne e asili nido). Ci lavoriamo e poi lo carichiamo :)

**Comment by olistik** [comment]
:metal: :smile:

**Comment by olistik** [comment]
@favoeva 

https://github.com/comune-desio/opendata/blob/master/scuole%20primarie%20-%20Desio.csv
https://github.com/comune-desio/opendata/blob/master/scuole%20secondarie%20di%20primo%20grado%20-%20Desio.csv
https://github.com/comune-desio/opendata/blob/master/scuole%20secondarie%20di%20secondo%20grado%20-%20Desio.csv

quando riesci a darmi un ok sulla validità dei CSV li converto in GEOJSON :-)

**Comment by favoeva** [comment]
@olistik a me sembrano a posto (ho dovuto cambiare un paio di latutudini )
