### ISSUE TITLE
Associazioni culturali iscritte all'Albo comunale 

### ISSUE THREAD

**Issue by favoeva** [comune-desio/opendata#6]
@olistik  ecco il dataset delle associazioni culturali aggiornato al gennaio 2016 
è un dataset annuale gestito dal servizio Cultura del Comune di Desio e riguarda tutte (e solo) le associazioni iscritte all'albo comunale 
[ASSOCIAZIONI CULTURALI.zip](https://github.com/comune-desio/opendata/files/154677/ASSOCIAZIONI.CULTURALI.zip)

**Comment by olistik** [comment]
33bb1f8a21301263f4d641c4200f69596fec7bd7 e 9d51c60c94b8493bed4d4254cc97516ac01912d3 chiudono questa issue
